name: pizza_mobile_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lucide_icons_flutter: ^3.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  archify: ^1.1.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/global/
    - assets/images/splash/
    - assets/images/product/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 300
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 400
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 500
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 600
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 700
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 800
        - asset: assets/fonts/Figtree-Variable.ttf
          weight: 900
        - asset: assets/fonts/Figtree-Italic-Variable.ttf
          weight: 400
          style: italic
